export function translator(type: string) {
  const translations: { [key: string]: string } = {
    ALL: "Toutes productions",
    API: "Apicultures (nombre de ruches)",
    AUPA: "Autres productions animales",
    AUVOL: "Autres volailles de chair",
    BL: "Brebis lait",
    BV: "Brebis viande",
    CH: "Chèvres",
    CO: "Porcs charcutiers (valeurs fiables à partir de 2020)",
    LAR: "Lapines reproductrices",
    LA: "Lapins - estimation",
    PO: "Poules pondeuses",
    PC: "Poulets de chair",
    TR: "Truies reproductrices",
    VA: "Vaches allaitantes",
    VL: "Vaches laitières",
    HSAU: "Surfaces non comptabilisées dans la SAU des exploitations (Estives, zones de cueillette sauvage, Sylviculture, Surfaces non agricoles)",
    AQU: "Surfaces d'aquaculture (bassins)",
    CUEIL: "Zones de cueillette sauvage",
    SNA: "Surfaces non agricole (bâtiments, chemins, mares…)",
    SYLV: "Sylviculture",
    ESTIV: "Estives collectives",
    GCU: "Grandes cultures (dont légumes secs)",
    CE: "Céréales",
    OL: "Oléagineux",
    PR: "Protéagineux",
    LES: "Légumes secs",
    SF: "Surfaces Fourragères (dont prairies permanentes et temporaires, mais fourragers autres cultures fourragères, parcours ...)",
    STH: "Surfaces toujours en herbe (Prairies permanentes, landes et parcours)",
    AFO: "Autres surfaces fourragères (dont prairies temporaires et autres cultures fourragères)",
    FR: "Fruits (arboriculture dont fruits à coques, fruits frais et fruis de transformation)",
    FRB: "Baies (y compris fraises)",
    FRNP: "Fruits à noyau et à pépins",
    FRC: "Fruits à coque",
    AGR: "Agrumes",
    FRD: "Autres fruits et divers",
    FRTST: "Fruits tropicaux et sub-tropicaux",
    LE: "Légumes frais (yc maraichage sous serre ou de pein champ dont pomme de terre) les espèces ne sont pas détaillées",
    PP: "Plantes à parfum aromatiques et médicinales (PPAM)",
    VI: "Viticulture (dont raisin de table)",
    AU: "Autres surfaces entrant dans la SAU (dont cultures industrielles)",
    CIN: "Cultures industrielles (chanvre, canne à sucre…)",
    HLI: "Hors liste (gel annuel, engrais verts, surfaces non exploitées temporairement, champignonières...)",
  };

  return translations[type];
}
